apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  params:
    - name: name
      type: string
      default: "World"
  tasks:
    - name: echo-hello
      taskSpec:
        steps:
          - name: echo-hello
            image: ubuntu
            command: ["sh", "-c"]
            args:
              - |
                echo "Hello $(params.name)!"
    - name: echo-date
      taskSpec:
        steps:
          - name: echo-date
            image: ubuntu
            command: ["date"]
    - name: echo-build
      taskSpec:
        steps:
          - name: echo-build
            image: docker
            command: ["sh", "-c"]
            args:
              - |
                docker build --build-arg GIT_REVISION=$(git rev-parse HEAD) -t clickcount .
