apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  params:
    - name: name
      type: string
      default: "World"
  tasks:
    - name: echo-hello
      taskSpec:
        steps:
          - name: echo-hello
            image: alpine:3.14
            command: ["sh", "-c"]
            args:
              - |
                echo "Hello $(params.name)!"
    - name: echo-date
      taskSpec:
        steps:
          - name: echo-date
            image: alpine:3.14
            command: ["date"]
